server:
  port: 8088
  servlet:
    context-path: /example

spring:
  profiles:
    active: dev

  # 应用配置
  application:
    name: dynamic-threadpool-example

  # 动态线程池配置
  dynamic:
    thread-pool:
      server-addr: http://localhost:6691
      namespace: prescription
      item-id: ${spring.application.name}

# 日志配置文件地址
logging:
  config: classpath:logback.xml
