server:
  port: 6691

tenant: hippo

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hippo_manager?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: 12345678
    hikari:
      pool-name: Hikari
      connectionTimeout: 30000
      idleTimeout: 30000
      validationTimeout: 3000
      maxLifetime: 120000
      loginTimeout: 5
      minimumIdle: 5
      maximumPoolSize: 15
      connection-test-query: SELECT 1

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
